# action.yml

# GitHub will build an image from your Dockerfile,
# and run commands in a new container using this image.
name: 'Prepare Release Notes'
description: 'Lists recently merged PRs and updates the PR description with the list'
# used to pass inputs to the docker container. those will then be passed through
# the args
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
# In order for GitHub to recognize output variables, you must use a workflow
# command in a specific syntax: echo "::set-output name=<output name>::<value>"
outputs:
  changelog: # id of output
    description: 'The generated changelog'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_REPO: ${{ github.repository }}

branding:
  icon: 'file-text'
  color: 'purple'
