# action.yml

# GitHub will build an image from your Dockerfile,
# and run commands in a new container using this image.
name: 'Prepare Release Notes'
description: 'Drafts the release notes and stores it in an environment variable'
# used to pass inputs to the docker container. those will then be passed through
# the args
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  github_repo:
    description: 'GITHUB_REPO'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CHANGELOG_GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_REPO: ${{ inputs.github_repo }}

branding:
  icon: 'file-text'
  color: 'purple'
