on: [push]

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Preparing the Changelog
    steps:
    - name: Run changelog
      id: prepare_changelog
      uses: rpbaltazar/release-note-prep@v0.4.3
      with:
        github_token: ${{ secrets.github_token }}
    # Use the output from the `hello` step
    - name: Get the generated changelog
      run: echo "Prepare release result ${{ steps.prepare_changelog.outputs.changelog }}"
