on: [push]

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Preparing the Changelog
    steps:
    - name: Run changelog
      id: prepare_changelog
      uses: rpbaltazar/release-note-prep@building-github-action-for-script
      with:
        github_token: ${{ secrets.github_token }}
        github_repo: ${{ github.repository }}
    # Use the output from the `hello` step
    - name: Update PR description with RELEASE NOTES
      uses: kt3k/update-pr-description@v1.0.1
      with:
        pr_body: ${{ env.RELEASE_NOTES }}"
        github_token: ${{ secrets.github_token }}
